### ISSUE TITLE
추가 개발사항

### ISSUE THREAD

**Issue by xowns4817** [Plogging/Plogging_server#15]
orm적용, exception 모듈처리 등 리팩토링 작업이 어느정도 끝난거 같아요.

각자 남은 잔여 개발사항 및 개선해보고 싶은점을 자유롭게 논의해보면 좋을거 같아요.

저는 파일서버를 별도로 구축해서 따로 빼는 부분좀 검토해볼게요. 저희코드를 보면 파일업로드 및 접근을 api서버에서 호스팅 해주는 방식이라 api 처리서버와 파일 서버는 분리는게 맞다고 봐요. ( 의견있으시면 의견주세요 )
그리고 ssl 설정, 서버 로드벨런싱 처리(Docker swarm), redis sentinel, mongodb replicaset, github-jenkins 연동 자동배포를 배포된 서버에 붙일 예정입니다. ( 로컬환경 구현됨 )  시간이 좀 된다면 ELK stack으로 로그데이터 관리 정도 진행하려고 해요

유저쪽은 중복 로그인처리, 로그인세션관리 ( expire time을 없앴는데 계속 서버에 쌓아둘건지? 어떻게 관리할건지 논의필요), 로그인 몇회 실패시 몇분간 로그인 차단등 적용해볼것들이 많을거같아요. 

랭킹쪽은 redis를 쓰는데  메모리 디비라 데이터 유실에 대한 고민이 좀 필요할거 같아요.  redis aof, rdb나  데이터를 이중화 할 수 있는 방법을 생각해보면 좋을거 같아요. 물론, 제가 sentinel 설정하고 master/slave 서버를 별도 서버에 둘거라 이중화는 되겠지만..

물론 안하셔도 됩니다. 다만, 스터디 목적이니 해보는걸 추천해요.

관련해서 적용해보고 싶은 기술이나 추가로 개발하고 싶은 부분있으면 의견주세요.

**Comment by ganghee** [comment]
네 좋은 아이디어입니다.😃
1. 유저쪽에서는 중복 로그인 문제가 있다면 어떤게 있을까요?
2. 로그인 세션관리에서는 서버에 계속 저장되어 있는게 맞다고 봐요 전에는 세션에 사용자 정보(userId)가 들어있는데 지금은 세션 아이디만 가지고 있으니 계속 저장되어도 문제가 없을 것 같아요.
3. 로그인 10회 실패시 10분간 정지 어떤가요? 구현해본적이 없지만 구현하는데는 어렵지 않을것 같아요. 그래도 실패 허용횟수, 로그인 정지 시간은 같이 이야기해봐요 의견주세요~
4. 휴면 계정도 있으면 좋을 것 같아요 1년 동안 로그인하지 않으면 휴면계정으로 되어 랭킹 정보랑 플로깅 정보 삭제 되게끔요

랭킹 쪽에서 주간 월간 마다 자동으로 초기화하는 것도 추가하면 좋을 것 같아요

**Comment by xowns4817** [comment]
1번 부터 답변드릴게요 ~

1. 중복 로그인 문제가 있다기 보다 지금 저희 코드를보면 브라우저 A, B가 같은 아이디로 로그인을 하면 레디스에 키 2개가 생기겠죠? 근데, 키의 값을보면 같은 userId가 있을거에요. 즉, 같은 아이디로 동시에 로그인가능하도록 되어있어요.  중복 로그인을 허용안한다고 하면 이걸 한시점에 로그인 할 수 있는 유저를 1명을 제한하는거죠.  정책은 정하기 나름인데 기존에 로그인 했던사람을 유지시킬수도 있고(해당 아이디로 다른 브라우저에서 로그인했다면 로그인안됨), 새로 로그인 되는 사람을 로그인 시킬수도있어요. (기존 로그인 됬던 유저 로그인 풀림 )

2. 지금도 서버에서는 세션아이디와 사용자 정보를 가지고있어요. 세션아이디는 키값이고 이 키값으로 유저 정보를 조회해야 어떤 유저의 요청인지 서버에서 알 수 있지요.  그리고, 로그인을 안풀리게 하려고 세션의 expire를 제거했는데, 이거  expire을 제거하지 말고 ttl을 좀 길게 가져갑시다. 확인해보니 요청하면 ttl이 처음세팅했던 값으로 초기화되니 문제는 안될거같아요. 세션을 명시적으로 로그아웃할때까지 가지고 있는게 아니라 ttl 설정기간까지 가지고 있다고 보시면 되요. 예를들어, ttl이 3일이면 3일내에 요청을 한번이라도 하면 그 요청시점으로 다시 ttl값이 3일이 될 것이고, 3일내에 요청을 안했다면 세션키 삭제되는 식으로..
3. 보통은 기본적으로 5회실패시 30분 정지로 알고있어요~ 이걸 구현하려면 서버 내부에서 클라의 로그인 접근횟수, 그에 따른 response값 분기정도가 필요하겠네요.  그런데, 로그인 접근횟수 변수를 application 코드단에서 처리하면 안될거 같구 redis 사용해주세요. ( api 서버가 여러대이므로...)
4.  네. 이건 유저 테이블에  휴면계정 flag값, 마지막 로그인시간 정도추가하고 배치로 하루에 한번씩 유저 테이블조회해서 휴면계정으로 전환하면될거같아요.

글로쓰려니 말이 길어졌네요.. 관련해서 이야기하실부분있으시면 따로 회의를 진행해도 좋을거같아요
