### ISSUE TITLE
Code Refactoring ( API, Business, Db handling 로직 분리 및 exception 처리모듈 공통화)

### ISSUE THREAD

**Issue by xowns4817** [Plogging/Plogging_server#9]
지금 코드를 보면 router 안에 business 로직, 디비 연동 로직 들이 섞여있어서  **API 요청단**,  **Business로직 처리단**, **디비 로직 처리단** 이렇게 세부분으로 나눠서 리팩토링 하면 좋을거 같아요.

그리고 node에도 try-catch 말고 exception을 handling하는 패턴? 이 있을거 같긴한데 ( exception을 exception 클래스로 던져서 그곳에서 모든 excepiton처리하는 방식인데 spring의 @ControllerAdvice라고 보시면 될거같아요) 

이부분들은 제가 좀 설계해볼게요~~ 의견있으시면 의견주세요.

**Comment by fuzzysound** [comment]
랭킹쪽은 제가 한번 해볼게요. 이게 테스트를 쉽게 만들 수 있도록 해줄 수도 있다는 생각이 드네요.

**Comment by fuzzysound** [comment]
말씀하신 걸 요약해보면 이렇게 될 것 같네요. 제 생각을 좀 더 덧붙여봅니다.
1. router와 controller, model의 분리: 비즈니스 로직은 전부 controller에 붙어야겠고, model은 ORM, ODM 구현과 동시에 리팩토링되면 좋을것 같네요. MariaDB는 sequalize로, MongoDB는 mongoose로 하면 될거 같고, 레디스의 경우는 별도 라이브러리는 필요없지만 역시 모델 단으로 분리해서 거기서 모든 걸 통제하게 하면 될 것 같습니다. 이렇게 하면 테스트 만들때도 모델 오브젝트만 mock해주면 되니 더 편해질 것 같습니다.
2. 예외처리: index.js의 `app.use((err, req, res, next) => {...})`에서 처리하는게 best practice인 것 같습니다(https://expressjs.com/ko/guide/error-handling.html). 지금 각 모듈에서 쓰고있는 try-catch는 다 빼는 게 맞는 것 같고, throw.js 같은 걸 써서 미들웨어 몇 개 만들면 될 것 같습니다.

결론은... 리팩토링이 끝난 다음에 테스트코드를 만드는 게 맞는 것 같습니다. 그래서 역할분담을 다시 해야 할 것 같구요. 태준님이 제때 잘 지적해주신 것 같습니다. 그냥 넘어갔으면 막 짰다가 또 갈아엎고 난리날 뻔 했네요.

저는 express쪽 best practice를 좀 더 공부해 보겠습니다.

**Comment by ganghee** [comment]
Error 인터페이스를 사용해본적이 있어요.
![image](https://user-images.githubusercontent.com/35513039/105658714-655f7b00-5f0a-11eb-9ece-072addbe337c.png)
이런 구조로 구현한 적이 있어요!

**Comment by xowns4817** [comment]
@fuzzysound 의견 감사합니다. 준현님~~  근데, orm 적용은 좀 더 생각이 필요할거같네요.  관련 내용 스터디기간 및 기존 구현된 코드변경이 많아질거 같습니다. 제생각은 위에서말씀드린 비지니스코드분리, exception  처리모듈 공통화 이 두 부분을  먼저 처리하는게 나을가같아요. 이 두 부분을 처리하면 구조가 새롭게 잡힐것이니 그것을 기반으로 orm적용을 검토해보면 좋을거같습니다.

**Comment by xowns4817** [comment]
@ganghee 내일 회의때 구조한번 설명해주시면 좋을거 같습니다!
